FROM scratch

ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.name="Label Schema Template - Docker Maven Plugin with Git" \
      org.label-schema.version="${VERSION}" \
      org.label-schema.vcs-url="${VCS_URL}" \
      org.label-schema.vcs-ref="${VCS_REF}" \
      org.label-schema.build-date="${BUILD_DATE}"
