FROM scratch

ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.name="Label Schema Template - Bash Subversion" \
      org.label-schema.version="1.0.0" \
      org.label-schema.vcs-url="${VCS_URL}" \
      org.label-schema.vcs-ref="${VCS_REF}" \
      org.label-schema.build-date="${BUILD_DATE}"
